# Generated by Django 5.1.6 on 2025-02-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customization_created_at_customization_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='jersey_type',
            field=models.CharField(choices=[('custom', 'Custom Jersey'), ('existing', 'Existing Jersey')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='customization',
            name='jersey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.jersey'),
        ),
    ]
