# Generated by Django 5.1.6 on 2025-02-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customization_jersey_type_alter_customization_jersey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='design',
        ),
    ]
