# Generated by Django 5.1.6 on 2025-03-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_items_alter_order_status_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='image',
        ),
        migrations.CreateModel(
            name='JerseyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jersey_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.jersey')),
            ],
            options={
                'ordering': ['order', '-is_primary'],
            },
        ),
    ]
