# Generated by Django 5.1.6 on 2025-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_pending', 'Return Pending'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_completed', 'Return Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
