# Generated by Django 5.1.6 on 2025-04-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jersey',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jersey',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jersey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='jersey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.jersey'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='jersey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.jersey'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='jersey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.jersey'),
        ),
    ]
