# Generated by Django 5.1.6 on 2025-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_jersey_created_at_jersey_description_jersey_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
