# Generated by Django 5.1.6 on 2025-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jersey',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jersey',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
