# Generated by Django 5.1.6 on 2025-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_jersey_average_rating_jersey_rating_sum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='total_ratings',
        ),
        migrations.AddField(
            model_name='jersey',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
