# Generated by Django 5.1.6 on 2025-04-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_jersey_rating_sum_remove_jersey_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='jersey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.jersey'),
        ),
    ]
